#!/bin/zsh

distro=$(lsb_release -c -s)

mkdir -p packages/$distro/binary-amd64
mkdir -p upstream/$distro

rm -rfv upstream/$distro/*

for f in *.tar.gz
do
    fullname=${f%.tar.gz}
    prefix=${fullname##*/}
    revision=${prefix##*-}
    no_revision_prefix=${prefix%-*}
    version=${no_revision_prefix##*-}
    no_version_prefix=${no_revision_prefix%-*}
    orig=upstream/$distro/$no_version_prefix\_$version.orig.tar.gz
    echo "processing $orig"
    cp -rf $f $orig
    pushd upstream/$distro
    tar xvzf $no_version_prefix\_$version.orig.tar.gz
    pushd $prefix/
    debuild -us -uc
    if [[ $? != 0 ]]
    then
	exit -1
    fi
    sudo mv ../$no_version_prefix\_$version-$revision\_amd64.deb ../../../packages/$distro/binary-amd64/
    if [[ $? != 0 ]]
    then
	exit -1
    fi
    popd
    popd
done

